linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: github.com/sagikazarmark/protoc-gen-go-kit

linters:
    presets:
        - bugs
        - unused
        - format
        - import
