project_name: protoc-gen-go-kit

builds:
  - env:
      - CGO_ENABLED=0
    ldflags: "-s -w -X main.version={{ .Version }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    stdin: ""
    args:
    - "sign-blob"
    - "--yes"
    - '--key={{ if index .Env "COSIGN_KEY"  }}{{ .Env.COSIGN_KEY }}{{ else }}{{ end }}'
    - "--output-signature=${signature}"
    - "--output-certificate=${certificate}"
    - "${artifact}"
    artifacts: archive

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'
